source "http://rubygems.org"

gemspec
gem 'paper_trail'
gem "reflect", :path => "lib/gems/reflect"
gem "followable", :path => "lib/gems/followable"
gem "trackable", :path => "lib/gems/trackable"
gem 'acts_as_tenant'