# Example playbook for installing Node.js from source.

- name: Get current node version
  shell: (node -v 2> /dev/null) | cut -f1 -d" "
  register: node_current_version
  sudo: False

- name: Node Version check
  debug: >
    msg="current version of Node is {{ node_current_version.stdout }} while were looking for {{ node_version }}"

- name: Node.js | Fetching node.js source
  get_url: url=http://nodejs.org/dist/{{node_version}}/node-{{node_version}}.tar.gz dest=/tmp/
  when: node_current_version.stdout != node_version
  sudo: True

- name: Node.js | Unpack node.js tarball
  command: tar zxf node-{{node_version}}.tar.gz chdir=/tmp
  when: node_current_version.stdout != node_version
  sudo: True

- name: Node.js | Configure
  shell: "/usr/bin/python ./configure --prefix={{node_path}} chdir=/tmp/node-{{node_version}}"
  when: node_current_version.stdout != node_version
  sudo: True

- name: Node.js | Make
  shell: "/usr/bin/make chdir=/tmp/node-{{node_version}}/"
  sudo: True
  when: node_current_version.stdout != node_version

- name: Node.js | Make install
  shell: "/usr/bin/make install chdir=/tmp/node-{{node_version}}/"
  when: node_current_version.stdout != node_version
  async: 1200
  poll: 30
  sudo: True
