- name: install webpack
  npm: name=webpack global=no path={{app_home}}

- name: install coffee-loader
  npm: name=coffee-loader global=no path={{app_home}}

- name: install s3
  npm: name=s3 global=no path={{app_home}}

- name: install yamljs
  npm: name=yamljs global=no path={{app_home}}

- name: install chunk-manifest-webpack-plugin
  npm: name=chunk-manifest-webpack-plugin global=no path={{app_home}}

- name: install compression-webpack-plugin
  npm: name=compression-webpack-plugin global=no path={{app_home}}

