# Import seed database

- name: Create default database
  mysql_db: name=${database.name} state=present login_user=${database.user} login_password=${database.password}
  sudo: True
  ignore_errors: yes

- name: Copy existing database to remote server
  copy: src=templates/seed_data/test.sql.bz2 dest=/tmp/${database.name}.sql.bz2
  sudo: True

- name: Uncompress database dump
  command: /bin/bunzip2 /tmp/${database.name}.sql.bz2 creates=/tmp/${database.name}.sql
  sudo: True

- name: Import database
  mysql_db: name=${database.name} login_user=${database.user} login_password=${database.password} state=import target=/tmp/${database.name}.sql
  ignore_errors: yes
  sudo: True

- name: Remove database dump
  file: path=/tmp/{database.name}.sql state=absent
  sudo: True
