- name: Compress avatars
  local_action: shell zip -r templates/seeds_for_local_dev/avatars.zip ../public/system/avatars
  sudo: False

- name: Copy sample avatars
  copy: src=templates/seeds_for_local_dev/avatars.zip dest=$app_home
  sudo: False

- name: Uncompress avatars directory
  shell: unzip $app_home/avatars.zip -d $app_home
  ignore_errors: yes
  async: 60
  poll: 10
  sudo: False

- name: Remove avatars zip
  file: path=$app_home/avatars.zip state=absent
  sudo: False

- name: Cache avatars
  shell: $source && cd $app_home && RAILS_ENV=$rails_environment bundle exec rake cache:avatars
  sudo: False