cir_header = "black"


ExpandableSection = ReactiveComponent
  displayName: 'ExpandableSection'

  render: -> 
    label = @props.label
    text = @props.text 

    expanded = @local.expanded 

    symbol = if expanded then 'fa-chevron-down' else 'fa-chevron-right'

    DIV null,
        

      DIV 
        onClick: => @local.expanded = !@local.expanded; save(@local)

        style: 
          fontWeight: 600
          color: cir_header
          cursor: 'pointer'
          marginTop: 12
          fontSize: 22

        SPAN 
          className: "fa #{symbol}"
          style: 
            opacity: .7
            position: 'relative'
            left: -3
            paddingRight: 6
            display: 'inline-block'
            width: 20


        SPAN 
          style: {}

          label 

      if expanded 
        text 

# customizations['cir'].NonHomepageHeader = customizations['cir'].HomepageHeader

window.HomepageHeader = ReactiveComponent
  displayName: 'HomepageHeader'

  render: ->

    loc = fetch('location')

    homepage = loc.url == '/'

    section_style = 
      marginBottom: 20
      color: 'black'

    paragraph_heading_style = 
      display: 'block'
      fontWeight: 400
      fontSize: 40
      color: cir_header

    paragraph_style = 
      fontSize: 18
      color: '#666'
      paddingTop: 10
      display: 'block'


    statement = 
      Opponent: [
        "M97 would be the most costly and damaging tax increase in Oregon history.  Its $6 billion tax hike would hurt Oregon small businesses and consumers by increasing prices for almost all goods and services they buy, with no guarantee of how the funds would be spent."
        "Sponsors claim the tax only affects large corporations. But studies by the nonpartisan Legislative Revenue Office (LRO) and Northwest Economic Research Center (NERC) funded by M97’s sponsors, both found that most of the tax would be passed on to Oregon consumers through higher costs for everything from food, clothing, cars and housing to gas, electricity, insurance and healthcare. LRO estimated M97 would increase costs for a typical Oregon family by $600 per year."
        "Both studies also show the impacts would be regressive, by costing low- and middle-income families a higher percentage of their incomes than upper-income families. This would especially hurt rural counties, where average incomes are lower than urban/suburban counties."
        "Former State Economist Tom Potiowsky, who led the NERC study, said 97's tax is “like a sales tax on steroids.” A recent news story revealed that when sponsors tried pressuring him to say 97’s tax on C Corps wouldn’t be regressive for consumers Potiowsky said: “Applying [a gross receipts tax] to a narrow group of C corporations does not make regressivity go away.”"
        "Both studies also agreed that M97 would cause the loss of tens of thousands of private-sector jobs, by increasing operating costs for both large employers and small businesses statewide."
        "M97 would arbitrarily and unfairly make some businesses bigger losers than others.  It taxes C Corps but exempts S Corps and B Corps that sell the same products and make as much or more money. It would especially hurt businesses that have slim profit margins, like farms and grocery stores, and those that are already struggling. It would also burden startup companies that initially have little or no profit, making Oregon one of the worst states in which to locate a new business."
        "M97 also hurts nonprofits and local governments, since they would face increased costs of electricity, gas, insurance, healthcare and other goods and services."
        "We all want ample funding for education, healthcare and other vital services but M97 doesn’t provide a guarantee or accountability of where revenues will go. Legislative Counsel confirmed that the legislature “may appropriate revenues generated by the measure in any way it chooses.”  The July 20 Portland Tribune editorial noted: “The Legislature can spend the available money in any way it sees fit—on pensions, prisons or pet projects.”
        M97 is a damaging tax plan that would hurt small businesses, cause thousands of Oregon workers to lose their jobs and put the greatest burden on low- and middle-income families and seniors on fixed incomes.
        That’s why NO on 97 is urged by a broad coalition of small businesses, farmers, organizations, consumers, taxpayers and editorials in nearly every major newspaper."
      ],
      Proponent: [
        "Measure 97 makes large and out-of-state corporations pay more in taxes so Oregon families can have the schools, health care, and dignified retirement we deserve."
        "According to two separate independent studies, corporations pay lower taxes in Oregon than any other state. Large and out-of-state corporations like Bank of America, Comcast, Wal-Mart, and Monsanto make hundreds of millions of dollars from the business they do in Oregon but pay lower taxes here than anywhere else in the nation. "
        "At the same time, Oregon families are taking home $1,000 to $2,000 less each year, while corporate profits have risen 170% over the last decade. Oregon families are struggling and large corporations are not paying their fair share."
        "Low corporate taxes hurt schools and families. Oregon’s high school graduation rates are the 4th lowest in the country. 383,000 Oregonians still have no health insurance, and premiums are too expensive. 21,000 more seniors live in poverty today than a decade ago. If we pass Measure 97, we can address these problems."
        "Measure 97 increases the corporate tax only on C corporations and only on their sales above $25 million. 82% of the money raised comes from corporations headquartered outside Oregon. 85% of the money comes from corporations with more than $100 million in sales in Oregon. Less than 1% of Oregon businesses will be affected."
        "Measure 97 will hold big, out-of-state corporations accountable to paying their fair share of taxes. In 2013, 530 C corporations used tax credits to reduce their Oregon tax bill to $0, shorting the state by nearly $8.77 million in revenue. Additionally, because corporations hide profits overseas, Oregon loses $283 million per year in corporate income tax revenues. Measure 97’s simple, effective rate increase prevents corporations from exploiting off-shore loopholes." 
        "Money raised by Measure 97 is sorely needed, and will make a real difference in people’s lives. Oregon will be able to hire 6,000 new teachers, make sure every child in Oregon has health care, and allow 20,000 more Oregon seniors to afford to stay in their own homes when they retire by providing in-home care. "
        "Large corporations like Comcast and Kroger that oppose Measure 97 say Oregonians and not corporations will pay this new tax. Whenever we ask corporations to do their part they use scare tactics and threaten higher prices — economic data shows those threats are empty. Corporations charge the same for their products in every state, regardless of state taxes." 
        "Measure 97 gives Oregon families a chance for a better life. It will improve our schools and graduation rates, make healthcare affordable, and help our aging parents and grandparents retire with dignity."
      ]


    claims = 
      Opponent: [{
        statement: 'M97 would impose $6 billion in new taxes on sales of goods and services in Oregon: everything from food, clothing, cars and housing to gas, utilities, prescriptions and healthcare. It would be the largest, most damaging tax increase in state history.', 
        sources: [
          {text: 'Measure 97 Section 1'}, 
          {text: 'Portland Tribune, July 21', link: 'http://bit.ly/portlandtribune_tax-increase-threatens-family-budgets'},
          {text: 'LRO impact brief', link: 'http://bit.ly/CIRsources'}
        ]},{
        statement: 'M97 unfairly taxes sales, not profits. It would require businesses to pay 2.5% on sales even when they make no profit or lose money. That would especially hurt businesses that have slim profit margins, like grocery stores, medical clinics and farms.'
        sources: [
          {text: 'Measure 97 Section 1'}, 
          {text: 'Forbes', link: 'http://bit.ly/forbes_least-profitable-businesses'},
          {text: 'LRO impact brief', link: 'http://bit.ly/CIRsources'}
        ]},{
        statement: 'A nonpartisan study by the Legislative Revenue Office says M97\'s tax would increase costs consumers pay for essential goods and services, costing a typical family $600 more per year. A former State Economist said it\'s "like a sales tax on steroids."'
        sources: [
          {text: 'Legislative Revenue Office IP 28 Description and Analysis, table 1', link: 'http://bit.ly/OregonLRO_IP28-Research-Report'},
          {text: 'East Oregonian July 30', link: 'http://bit.ly/capitalbureau_gross-receipts-tax-on-steroids'},
          {text: 'LRO cost estimate to households', link: 'http://bit.ly/CIRsources'},
          {text: 'Shopping cart study', link: 'http://bit.ly/taxfoundation_IP28-would-raise-prices'}
        ]},{
        statement: 'A nonpartisan Legislative Revenue Office study shows 97\'s tax is regressive. It would increase consumer costs for food, medicine, clothing, housing, utilities and other essential goods and services, hurting families who can least afford it the most.'
        sources: [
          {text: 'Legislative Revenue Office IP 28 Description and Analysis, page 12 and table 11', link: 'http://bit.ly/OregonLRO_IP28-Research-Report'},
          {text: 'Shopping cart study', link: 'http://bit.ly/taxfoundation_IP28-would-raise-prices'},
          {text: 'ECONorthwest comparison of studies', link: 'http://bit.ly/CIRsources'},
        ]},{
        statement: 'M97 would hurt all Oregon employers, large and small, by increasing their operating costs and making them less competitive. The sponsors\' own study and the legislative study agree: M97 would cause the loss of tens of thousands of private sector jobs.'
        sources: [
          {text: 'Legislative Revenue Office IP 28 Description and Analysis, page 14', link: 'http://bit.ly/OregonLRO_IP28-Research-Report'},
          {text: 'ECONorthwest comparison of studies', link: 'http://bit.ly/CIRsources'},
        ]},{
        statement: '97 doesn’t guarantee the revenues will go to schools, healthcare or anything else. The Legislative Counsel Committee confirmed that the legislature “may appropriate revenues generated by the measure in any way it chooses.” It’s a blank check.'
        sources: [
          {text: 'Legislative Counsel Committee letter', link: 'http://bit.ly/CIRsources'},
          {text: 'Portland Tribune, July 2', link: 'http://bit.ly/portlandtribune_tax-increase-threatens-family-budgets'},
          {text: 'ECONorthwest testimony before the Fiscal Impact Statement Committee', link: 'http://bit.ly/CIRsources'},
          {text: 'Attorney General opinion, 37 Op Atty gen 599 (1975)', link: 'http://bit.ly/CIRsources'},

        ]},{
        statement: 'M97 makes it harder for local stores to compete with big chains. Chains ship and sell their own products and would pay 2.5%. Local stores get products via manufacturers and distributors who\'d each pay the tax, so their costs could go up 7.5% or more.'
        sources: [
          {text: 'Legislative Revenue Office IP 28 Description and Analysis, pages 11-12', link: 'http://bit.ly/OregonLRO_IP28-Research-Report'},
          {text: '"Tax on a Tax"" chart', link: 'http://bit.ly/CIRsources'},
          {text: 'Analysis by RCG Economics', link: 'http://bit.ly/CIRsources'},
        ]}
      ]

      Proponent: [{
        statement: 'M97 raises the corporate minimum tax on sales above $25 million on large and out-of-state C corporations, affecting less than 1% of businesses in Oregon. Money raised must fund Oregon’s early childhood education, K-12, healthcare, and senior services', 
        sources: [
          {link: 'http://oregonvotes.org/irr/2016/028text.pdf'}, 
          {link: 'https://www.oregonlegislature.gov/lro/Documents/IP%2028%20-%20RR%203-16.pdf'}, 
        ]},{
        statement: 'Oregon’s schools and critical services have been underfunded for decades, because large and out-of-state corporations don’t pay their fair share in taxes. In fact, Oregon ranks 50th in corporate taxes nationwide. Oregon families deserve better', 
        sources: [
          {link: 'http://www.ode.state.or.us/superintendent/priorities/2014-qem-report-volume-i-final--corrected.pdf'}, 
          {link: 'http://www.andersoneconomicgroup.com/Portals/0/AEG%20Tax%20Burden%20Study_2016_FINAL.pdf'}, 
          {link: 'http://www.ocpp.org/media/uploads/pdf/2016/06/rpt20160629-corporate-tax-shift_fnl.pdf'}, 
        ]},{
        statement: 'M97 would raise $3B annually, allowing for major investments in education, healthcare and senior services. This revenue could improve Oregon’s low graduation rates, make healthcare more accessible, and provide 20,000 more seniors with in-home care', 
        sources: [
          {link: 'https://www.oregonlegislature.gov/lro/Documents/IP%2028%20-%20RR%203-16.pdf'}, 
          {link: 'http://www.ode.state.or.us/superintendent/priorities/2014-qem-report-volume-i-final--corrected.pdf'}, 
          {link: 'http://www.oregonhealthequity.org/wp-content/uploads/2015/11/OHEA_MendtheGap_Web.pdf'}, 
          {link: 'https://www.pdx.edu/nerc/sites/www.pdx.edu.nerc/files/Retirement%20Security%20Final%20Report.pdf'},             
        ]},{
        statement: 'Without new taxes from large corporations, Oregon faces an estimated $750M a year of new budget cuts. This means deep cuts in every department and every school district. M97 would raise $3B a year to fund education, healthcare, and senior services', 
        sources: [
          {link: 'http://voteyeson97.org/wp-content/uploads/2016/08/A-Better-Oregon-report-8-1-16-final.pdf'}, 
          {link: 'http://www.statesmanjournal.com/story/news/politics/2016/07/11/why-oregon-budgeting-feast-and-famine/86944656'}, 
        ]},{
        statement: 'Because only large corporations pay M97, it will help small businesses be more competitive. M97 sets new corporate minimums that close corporate tax loopholes. A better educated workforce also means more qualified workers — which bolsters the economy', 
        sources: [
          {link: 'http://oregonvotes.org/irr/2016/028text.pdf'}, 
          {link: 'http://voteyeson97.org/oregon-families-pay-so-why-dont-corporations'}, 
          {link: 'http://www.oregonlive.com/education/index.ssf/2015/01/lack_of_technical_education_pr.html'},             
        ]},{
        statement: 'Oregon’s schools and critical services have faced cuts for decades. Since 1990, every OR governor has tried to fix budget shortfalls and stop the cuts. Oregonians can’t afford to wait any longer. Research and polls show M97 can finally fix this', 
        sources: [
          {link: 'https://icitizen.com/insights/oregon-poll-results-june-2016/'}, 
          {link: 'http://www.statesmanjournal.com/story/news/politics/2016/07/11/why-oregon-budgeting-feast-and-famine/86944656/'}, 
          {link: 'http://ouroregon.org/cuts-are-not-the-solution/'},     
          {link: 'http://klcc.org/post/oregon-school-funding-still-challenge-25-years-after-measure-5'}
        ]},{
        statement: 'Voters should ask themselves: Should large and out of state corporations pay their fair share in Oregon taxes? Do Oregon kids deserve good schools? Should all families have affordable health care? Should seniors get a dignified retirement?', 
        sources: []},
      ]

    DIV
      style:
        position: 'relative'
        width: HOMEPAGE_WIDTH()
        margin: 'auto'

      A 
        href: 'http://healthydemocracy.org'

        IMG
          style: 
            paddingTop: 10
            width: '296px'
            display: 'block'
            position: 'relative'
            left: -42

          src: asset('CIR/healthy-democracy-logo.png')


      ProfileMenu()

      if homepage 

        DIV 
          style: 
            padding: '20px 0'
            #marginTop: 50

          DIV 
            style: 
              width: HOMEPAGE_WIDTH()
              margin: 'auto'


            DIV 
              style: section_style


              SPAN 
                style: _.extend {}, paragraph_heading_style, 
                  marginTop: 10

                """Please help identify the most important question for our Citizen Panel to 
                   answer about Ballot Measure 97"""
              
              SPAN 
                style: paragraph_style
                """Below you will find official information about this measure, as well as claims that 
                   supporters and opposers of the measure are making. Additional information can be 
                   found on """

                A 
                  href: 'https://ballotpedia.org/Oregon_Business_Tax_Increase_Initiative_(2016)'
                  target: '_blank'
                  style: 
                    textDecoration: 'underline'
                    color: '#159ed9'

                  'ballotpedia.org'
                '.'


              SPAN 
                style: paragraph_style
                """After perusing this information, please give us your opinion about the question whose 
                   answer will make the biggest impact on whether you will vote for or against this 
                   measure. We will be ending the online input on Tuesday, August 16 in time to have 
                   your question printed in the official CIR Citizen Panel Manual."""

            DIV 
              style: section_style


              SPAN 
                style: 
                  display: 'block'
                  fontWeight: 400
                  fontSize: 28
                  color: cir_header

                """Measure 97: Oregon Business Tax Increase Initiative"""
        
              SPAN 
                style: paragraph_style

                """Increases corporate minimum tax when sales exceed $25 million; funds education, healthcare, senior services"""

              ExpandableSection
                label: 'Explanatory Statement'
                text: 
                  DIV null,
                    DIV style: paragraph_style,
                      "Ballot Measure 97 increases the corporate minimum tax for corporations with at least $25 million in Oregon sales. Currently, Oregon C corporations pay the higher of either an excise tax or a minimum tax based on the corporation’s sales in Oregon."
                    DIV style: paragraph_style,
                      "Ballot Measure 97 increases the annual minimum tax on corporations with Oregon sales of more than $25 million. It imposes a minimum tax of $30,001 plus 2.5 percent of amount of sales above $25 million. Oregon sales under $25 million would not be affected."
                    DIV style: paragraph_style,
                      "Ballot Measure 97 exempts “benefit companies” from the increased rate of minimum tax. “Benefit companies” are defined under Oregon law."
                    DIV style: paragraph_style,
                      "Ballot Measure 97 states that revenues generated from the increase in the corporate minimum tax are to be used to provide additional funding for education, healthcare and services for senior citizens."                    


              ExpandableSection
                label: 'Estimate of Financial Impact'
                text: 
                  DIV null,
                    DIV style: paragraph_style,
                      "The financial impact on state revenues is anticipated to be $548 million in new revenue in the 2015-17 biennium; $6.1 billion in the 2017-19 biennium and $6.0 million in the 2019-21 biennium. The annual financial impact on revenue would be approximately half of the biennial revenue amount."
                    DIV style: paragraph_style,
                      "The financial impact on state expenditures is indeterminate. The increased revenue will trigger increased expenditures by the state in the areas of public early childhood and kindergarten through grade 12 education, health care, and senior services, but the exact amount and the specific uses within the three identified programs cannot be determined."
                    DIV style: paragraph_style,
                      "There is no direct financial effect on local government expenditures or revenues."




              for section in ['Proponent', 'Opponent']


                ExpandableSection
                  label: "#{section} Claims"
                  text: 
                    DIV null,
                      for claim, idx in claims[section]
                        DIV 
                          style: _.extend {}, paragraph_style, 
                            marginLeft: 22
                            marginTop: 10

                          DIV 
                            style: 
                              fontWeight: 600
                              textDecoration: 'underline'
                            "Claim #{idx + 1}"
                          DIV 
                            style: {}

                            claim.statement

                          if claim.sources?.length > 0                           
                            UL 
                              style: 
                                marginLeft: 28
                                marginTop: 5

                              for src in claim.sources
                                LI 
                                  style: 
                                    listStyle: 'outside'

                                  if src.link 
                                    A 
                                      href: src.link 
                                      target: '_blank'
                                      style: 
                                        textDecoration: 'underline'
                                        color: '#159ed9'

                                      src.text or src.link
                                  else 
                                    src.text 
                      DIV 
                        style: 
                          marginLeft: 22
                          marginTop: 10
                        ExpandableSection
                          label: "#{section} Position Statement"
                          text: 
                            DIV 
                              style: 
                                marginLeft: 22

                              for para in statement[section]
                                DIV style: paragraph_style,
                                  para 



