- name: Write memcached.conf
  action: template src=templates/memcached.cnf.j2 dest=/etc/memcached.conf mode=0644
  sudo: True

- name: Restart memcached
  service: name=memcached state=started
  sudo: True