- name: Update system
  command: /usr/bin/apt-get update
  sudo: True

- name: Upgrade system
  command: /usr/bin/apt-get upgrade
  sudo: True

- name: Installs ruby building dependencies
  apt: pkg=$item state=latest install_recommends=no
  with_items: $deps
  sudo: True