- name: Update system
  command: /usr/bin/apt-get update --assume-yes
  sudo: True

- name: Upgrade system
  command: /usr/bin/apt-get upgrade --assume-yes
  sudo: True

- name: Installs ruby building dependencies
  apt: pkg={{item}} state=latest install_recommends=no
  with_items: deps
  sudo: True

- name: Install aws cli
  command: pip install awscli
  sudo: True