- name: Install passenger
  shell: "{{source}} && {{path}} gem install passenger --no-rdoc --no-ri"
  sudo: False

- name: Rbenv rehash
  shell: "{{source}} && {{path}} rbenv rehash"
  sudo: False

- name: Install passenger nginx module
  shell: "{{source}} && passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx --extra-configure-flags=--with-http_ssl_module creates=/opt/nginx"
  sudo: True

- name: Set Passenger Path
  shell: "{{source}} && passenger-config --root | cut -f1 -d\" \""
  register: passenger_root
  sudo: False

- name: Create passenger agents
  shell: "{{source}} && rake nginx chdir={{passenger_root.stdout}} creates={{passenger_root.stdout}}/agents/PassengerWatchdog"
  sudo: True # False #TODO: make sure it is ok to install under sudo
