- name: Install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=$rbenv_path
  sudo: False

- name: Create rbenv plugin directory
  file: path=$rbenv_path/plugins/ owner=$user group=$user state=directory
  sudo: False

- name: Install ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=${rbenv_path}/plugins/ruby-build
  sudo: False

- name: Add rbenv and shims to bashrc
  lineinfile: dest=~/.profile line='export RBENV_ROOT=${rbenv_path}; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(rbenv init -)"' regexp=rbenv*
  sudo: False

- name: Add rbenv and shims to root bashrc
  lineinfile: dest=/root/.profile line='export RBENV_ROOT=${rbenv_path}; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(rbenv init -)"' regexp=rbenv*
  sudo: True

- name: Add rbenv and shims to skel profile
  lineinfile: dest=/etc/skel/.profile line='export RBENV_ROOT=${rbenv_path}; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(rbenv init -)"' regexp=rbenv*
  sudo: True


#note: this could be dangerous if server is not just hosting considerit
# - name: Copy over root profile
#   shell: cp /etc/skel/.bashrc /root/.bashrc creates=/root/.profile
#   sudo: True

# - name: Add rbenv and shims to root path
#   lineinfile: dest=/root/.bashrc line='export PATH="/home/$user/.rbenv/bin:$ruby_home:$PATH"' regexp=rbenv*
#   sudo: True

- name: Get current ruby version
  shell: $source && $path rbenv version | cut -f1 -d" "
  register: ruby_current_version
  sudo: False

- name: Ruby Version check
  debug: msg="current version of Ruby is {{ ruby_current_version.stdout }} while we're looking for {{ ruby_version }}"

- name: Install ruby
  shell: $source && $path rbenv install $ruby_version && $path rbenv global $ruby_version
  when: ruby_current_version.stdout != ruby_version
  async: 600
  poll: 30
  sudo: False

# - name: Set global rbenv version
#   shell: $source && $path rbenv global $ruby_version
#   when: ruby_current_version.stdout != ruby_version
#   sudo: False

- name: Install bundler
  shell: $source && $path gem install bundler --no-rdoc --no-ri && $rbenv_home/rbenv rehash
  sudo: False

- name: Update gems
  shell: $source && $path bundle install --gemfile=$app_home/Gemfile
  sudo: False