- name: Write mysqld.conf
  template: src=templates/mysql/mysqld.cnf.j2 dest=/etc/mysql/conf.d/mysqld.cnf
  sudo: True
  notify:
    - Restart mysql

- name: Write mysqld.conf
  template: src=templates/mysql/client.cnf.j2 dest=/etc/mysql/conf.d/client.cnf
  sudo: True
  notify:
    - Restart mysql

- name: Start mysql service
  service: name=mysql state=restarted
  sudo: True

- name: Change default pass for user root for mysql
  mysql_user: name=${database.user} password=${database.password}
  ignore_errors: yes
  sudo: True

- name: Create default database
  mysql_db: name=${database.name} state=present login_user=${database.user} login_password=${database.password}
  sudo: True