- name: Create /var/log
  file: path=/var/log/nginx owner=root state=directory
  sudo: True

- name: Create /etc/nginx
  file: path=/etc/nginx owner=root state=directory
  sudo: True

- name: Write nginx mime.types
  template: src=templates/nginx/mime.types.j2 dest=/etc/nginx/mime.types
  sudo: True

- name: Configure nginx as service
  template: src=templates/nginx/nginx.init.j2 dest=/etc/init.d/nginx mode=0755
  sudo: True

- name: Set Passenger Path
  shell: $source && passenger-config --root | cut -f1 -d" "
  register: passenger_root
  sudo: False

- name: Write nginx.conf
  template: src=templates/nginx/nginx.conf.j2 dest=/opt/nginx/conf/nginx.conf
  sudo: True
  notify:
    - Restart nginx

- name: Make virtual hosts directory
  file: path=/etc/nginx/conf.d owner=root state=directory
  sudo: True

- name: Create vhost for this site
  template: src=templates/nginx/sites/vhost.conf.j2 dest=/etc/nginx/conf.d/$app_name.conf mode=0755
  sudo: True
  when: server.name is defined

- name: Add nginx bootup script to bootup process
  shell: update-rc.d nginx defaults
  sudo: True