- name: check if database contains tables
  shell: > 
    mysql -u{{database.user}} -p{{database.password}} -Bse "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '{{ database.name }}';"
  register: countAppDatabaseTables
  sudo: False

# this is dangerous! It will blow out all data on a production server, it should only be run on a new install!
- name: Load database schema
  shell: "{{source}} && cd {{app_home}} && RAILS_ENV={{code.environment}} bundle exec rake db:schema:load"
  when: countAppDatabaseTables.stdout == "0"
  sudo: False