// Generated by CoffeeScript 1.10.0
(function() {
  var dict;

  require('./customizations');

  window.t = function(label, args) {
    var dictionary, lang;
    lang = customization('lang');
    if (dict[lang] == null) {
      throw "Sorry, don't support language " + lang;
    }
    dictionary = dict[lang];
    label = label.replace(/\ /g, '_');
    if (dictionary[label] == null) {
      throw "Can't translate " + label + " for language " + lang;
    }
    if (typeof dictionary[label] === 'function') {
      return dictionary[label](args);
    } else {
      return dictionary[label];
    }
  };

  dict = {};

  dict.en = {
    comment: 'comment',
    comments: 'comments',
    read_more: 'read more',
    select_these_opinions: 'Select these opinions',
    prev: 'prev',
    next: 'next',
    drag_from_left: function(args) {
      return "Drag a " + args.noun + " from the left";
    },
    drag_from_right: function(args) {
      return "Drag a " + args.noun + " from the right";
    },
    write_a_new_point: function(args) {
      return "Write a new " + args.noun;
    },
    or: 'or'
  };

  dict.spa = {
    comment: 'comentario',
    comments: 'comentarios',
    read_more: 'ver más',
    select_these_opinions: 'Selecciona estas opiniones',
    prev: 'anterior',
    next: 'siguiente',
    drag_from_left: function(args) {
      return "Arrastra un " + args.noun + " de la izquierda";
    },
    drag_from_right: function(args) {
      return "Arrastra un " + args.noun + " de la derecha";
    },
    write_a_new_point: function(args) {
      return "Escribe un nuevo " + args.noun;
    },
    or: 'ó'
  };

  _.extend(dict.en, {
    Log_in: 'Log in',
    Create_new_account: 'Create new account',
    Log_out: 'Log out',
    Edit_Profile: 'Edit Profile',
    Email_Settings: 'Email Settings',
    Introduce_Yourself: 'Introduce Yourself'
  });

  _.extend(dict.spa, {
    Log_in: 'Entrar',
    Create_new_account: 'Registrarse',
    Log_out: 'Salir',
    Edit_Profile: 'Editar Perfil',
    Email_Settings: 'Configuración de Email',
    Introduce_Yourself: 'Descríbete'
  });

  _.defaults(dict.spa, dict.en);

}).call(this);

//# sourceMappingURL=translations.js.map
