---
- name: Updates ConsiderIt
  git: repo=${code.repo} dest=$app_home version=${code.branch}
  # NOTE: if config/environments/production.rb is modified in the repo or on the server, there may be problems
  sudo: False

- name: Create database.yml
  template: src=templates/project/database.yml.j2 dest=$app_home/config/database.yml mode=400
  sudo: False

- name: Create local_environment.yml
  template: src=templates/project/local_environment.yml.j2 dest=$app_home/config/local_environment.yml mode=400
  sudo: False

- name: Initialize production configuration
  template: src=templates/project/production.rb.j2 dest=$app_home/config/environments/production.rb
  sudo: False

- name: Update gems
  shell: $source && bundle install --gemfile=$app_home/Gemfile && rbenv rehash
  sudo: False

- name: Run database migration
  shell: $source && cd $app_home && RAILS_ENV=$rails_environment bundle exec rake db:migrate
  sudo: False

#TODO: handle AWS cloudfront at all?
- name: Precompile assets
  shell: $source && cd $app_home && RAILS_ENV=$rails_environment RAILS_GROUPS=assets bundle exec rake assets:precompile
  ignore_errors: yes #if we don't have AWS S3 set up, asset sync will error out unnecessarily
  sudo: False

- name: Flush memcache
  shell: echo "flush_all" | nc localhost 11211
  ignore_errors: yes
  async: 10
  poll: 2
  sudo: False

- name: Restart cron and delayed_job
  shell: $source && cd $app_home && RAILS_ENV=$rails_environment bundle exec whenever -w && RAILS_ENV=$rails_environment script/delayed_job restart
  sudo: False

# TODO: need to Ensure Passenger is running
- name: Notify Passenger to reset server
  shell: touch $app_home/tmp/restart.txt
  sudo: False
