---
- name: Updates ConsiderIt
  git: repo=${code.repo} dest=$app_home version=${code.branch}
  # NOTE: if config/environments/production.rb is modified in the repo or on the server, there may be problems

- name: Initialize production configuration
  template: src=templates/project/production.rb.j2 dest=$app_home/config/environments/production.rb

- name: Update gems
  shell: $source && bundle install --gemfile=$app_home/Gemfile && rbenv rehash

- name: Run database migration
  shell: $source && cd $app_home && RAILS_ENV=$environment bundle exec rake db:migrate

#TODO: handle AWS cloudfront at all?
- name: Precompile assets
  shell: $source && cd $app_home && RAILS_ENV=$environment bundle exec rake assets:precompile
  ignore_errors: yes #if we don't have AWS S3 set up, asset sync will error out unnecessarily

- name: Flush memcache
  shell: echo "flush_all" | nc localhost 11211
  ignore_errors: yes
  async: 10
  poll: 2

- name: Restart cron and delayed_job
  shell: $source && cd $app_home && RAILS_ENV=$environment bundle exec whenever -w && RAILS_ENV=$environment script/delayed_job restart

# TODO: need to Ensure Passenger is running
- name: Notify Passenger to reset server
  shell: touch $app_home/tmp/restart.txt