- name: Checkout modified files to enable pulling
  shell: "{{source}} && cd {{app_home}} && git checkout config/environments/production.rb; git checkout db/schema.rb; git checkout public/robots.txt; git checkout config/schedule.rb"
  sudo: False

- name: Installs ConsiderIt
  git: repo={{code.repo}} dest={{app_home}} version={{code.branch}} accept_hostkey=true
  sudo: False
  ignore_errors: yes


- name: Create database.yml
  template: src=files/database.yml.j2 dest={{app_home}}/config/database.yml mode=400
  sudo: False

- name: Create local_environment.yml
  template: src=files/local_environment.yml.j2 dest={{app_home}}/config/local_environment.yml mode=400
  sudo: False

- name: Create schedule.rb
  template: src=files/schedule.rb.j2 dest={{app_home}}/config/schedule.rb mode=400
  sudo: False

- name: install node modules
  shell: cd {{app_home}} && npm install  # requirements in package.json
