- name: Initialize production configuration
  template: src=templates/production.rb.j2 dest={{app_home}}/config/environments/production.rb
  sudo: False
  when: code.environment == "production"

- name: Update gems
  shell: "{{source}} && bundle install --gemfile={{app_home}}/Gemfile && rbenv rehash"
  sudo: False

- name: Precompile and upload assets
  shell: "{{source}} && cd {{app_home}} && BUILD_PRODUCTION=1 node_modules/webpack/bin/webpack.js"
  sudo: False
  when: code.environment == "production"

- name: Initialize robots.txt
  template: src=templates/robots.txt.j2 dest={{app_home}}/public/robots.txt
  sudo: False
  when: code.environment == "production"
