---

- hosts: all
  name: Setting up the server to respond to crawling by bots for single page apps
  vars:
    # for tasks/node/setup_upstart
    service: crawlable
    description: Enabling crawling by bots on single page apps
    script_path: "/home/considerit/crawlable/"

  #vars_files:
  tasks:
    - include: tasks/node/install_nodejs.yml
    - include: tasks/node/install_phantomjs.yml  
    - include: tasks/node/install_crawlable.yml  
    - include: tasks/node/setup_upstart.yml
  #handlers:
