# good set of playbooks: https://github.com/francisbesset/ansible-playbooks/
#https://www.digitalocean.com/community/articles/how-to-install-rails-and-nginx-with-passenger-on-ubuntu

# In setting up daniels, I had to modify /etc/sudoers to change the secure_path because rbenv paths weren't accessible through sudo

---

- hosts: all
  name: Installing dependencies and Setting up the Rails environment
  vars: 
  vars_files:
    - global_vars/environment.yml
    - global_vars/dependencies.yml
    - global_vars/mysql_config_vars.yml
    - global_vars/memcached_config_vars.yml
    - global_vars/nginx_config_vars.yml    
  tasks:
    - include: tasks/install/install_deps.yml
    - include: tasks/install/configure_system.yml
    - include: tasks/install/install_memcached.yml
    - include: tasks/install/install_mysql.yml
    - include: tasks/install/configure_github.yml
    - include: tasks/deploy/install_considerit.yml
    - include: tasks/install/install_ruby.yml
    - include: tasks/install/install_passenger.yml
    - include: tasks/install/install_nginx.yml
    - include: tasks/install/setup_ssl.yml
    - include: tasks/install/start_nginx.yml
  handlers:
    - include: tasks/handlers.yml
