embed_assets: off

javascripts:
  workspace:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/jquery.corner.js
    - public/javascripts/jquery.noblecount.min.js
    - public/javascripts/jquery.qtip-1.0.0-rc3.js
    - public/javascripts/protovis-r3.3.js
    - public/javascripts/jquery.example.min.js
    - public/javascripts/jquery.jcarousel.min.js

stylesheets:
  common:
    - public/stylesheets/reset-min.css
    - public/stylesheets/jquery_ui/jquery-ui-1.8.4.custom.css
    - public/stylesheets/jquery_ui/jquery-ui-custom.css
    - public/stylesheets/considerit.css
