development:
  adapter: mysql2
  database: considerit2_dev
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  database: dub_test
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  database: dub_production
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock


