development:
  adapter: mysql
  database: considerit2_dev
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql
  database: considerit2_test
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql
  database: considerit2_production
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock


