development:
  adapter: mysql
  database: considerit2_dev
  username: root
  password: root
  host: localhost


test:
  adapter: mysql
  database: considerit2_test
  password: root
  host: localhost


production:
  adapter: mysql
  database: considerit2_production
  username: root
  password: root
  host: localhost



