development:
  adapter: mysql2
  database: considerit_dev
  username: root
  password: root
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: considerit_test
  password: root
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: considerit_production
  username: root
  password: root
  host: localhost
  encoding: utf8

