development:
  adapter: mysql2
  database: considerit
  username: root
  password: root
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: considerit
  password: root
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: considerit
  username: root
  password: root
  host: localhost
  encoding: utf8

