default:

  host: ''

  analytics:
    google: ''

  bitly: 
    user_name: ''
    api_key: ''

development: 
  default_to: default

test: 
  default_to: development

production:
  default_to: development