default:
  secret_token: ''
  secret_key_base: ''
  admin_email: ''
  analytics:
    google: ''

  bitly: 
    user_name: ''
    api_key: ''

  new_relic: ''

  aws:
    access_key_id: ''
    secret_access_key: ''
    fog_directory: ''
    cloudfront: ''

  domain: 
    localhost: 
      facebook:
        consumer_key: ''
        consumer_secret: ''

      twitter:
        consumer_key: ''
        consumer_secret: ''

      google:
        consumer_key: ''
        consumer_secret: ''

    127.0.0.1:
      facebook:
        consumer_key: ''
        consumer_secret: ''

      twitter:
        consumer_key: ''
        consumer_secret: ''

      google:
        consumer_key: ''
        consumer_secret: ''



development: 
  default_to: default

test: 
  default_to: development

production:
  default_to: development