default:

  analytics:
    google: ''

  bitly: 
    user_name: ''
    api_key: ''

  new_relic: ''

  aws:
    access_key_id: ''
    secret_access_key: ''
    fog_directory: ''
    
development: 
  default_to: default

test: 
  default_to: development

production:
  default_to: development