default:

  application_name: ''

  authentication:
    twitter:
      consumer_key: ''
      consumer_secret: ''
      oauth_token: ''
      oauth_token_secret: ''
    facebook:
      app_id: ''
      app_secret: ''

  analytics:
    google: ''

development: 
  default_to: default

test: 
  default_to: development

production:
  default_to: development