default:

  application_name: 'lvg'

  authentication:
    twitter:
      consumer_key: 'X6LCs8gXhfLU7f5ZlKg'
      consumer_secret: 'UmMdf7pHS01pAvX891AGDN0Hm1fmBgZ37fEuoNnjzI'
      oauth_token: '56741110-8v6mvFAMMXURiIb4JQlDQj8atQzhNxb2siMc5C0GX'
      oauth_token_secret: '4icVKCi5WfQsosYKFWzK1Eg6MTqu7xQIjMoAJhM'
    facebook:
      app_id: '154394447927854'
      app_secret: 'c1e6437b4bd76b2fb0bf8adc08665b88'

  analytics:
    google: ''

development: 
  default_to: default

test: 
  default_to: development

production:
  default_to: development