development: 
  app_name: 
    short: pso
    long: Living Voters Guide
  
  theme: pso
  
  meta:
    title: Youth Education Levy Campaign
    subtitle: Think through the different aspects of the education levy
    
  perform_authentication: true
  send_email: false
  
  home:
    call: Youth Education Levy Campaign
    subcall: Think through the different aspects of the education levy together
    values:
      - lead: Organize your thoughts
        follow: Write a pro/con list for different components of the levy.
      - lead: Uncover counterarguments
        follow: Think through the arguments people might make against your position. 
  
  socmedia:
    facebook:
      include_follow: false
      facebook_page: 
    twitter:
      include_follow: false
      twitter_page: 
  
  decisions:
    name: 
      short: levy component
      full: levy component
  
  footer:
    has_custom_resources: true
    resources:
      - title: Resources
        items:
          - anchor: League of Women Voters of Gr. Seattle
            link: http://sites.google.com/site/wavoter/ballot
            title: Voters Guide by the League of Women Voters
      
         
  
test: 
  default_to: development
  perform_authentication: true
  send_email: true


production:
  default_to: development
  perform_authentication: true
  send_email: true

