development: 
  app_name: 
    short: pso
    long: Living Voters Guide
  
  theme: pso
  
  meta:
    title: Youth Education Levy Campaign
    subtitle: Think through the different aspects of the education levy
    
  perform_authentication: true
  send_email: false
  
  home:
    call: Youth Education Levy Campaign
    subcall: Think through the different aspects of the education levy together
    values:
      - lead: Organize your thoughts
        follow: Write a pro/con list for different components of the levy.
      - lead: Uncover counterarguments
        follow: Identify arguments people might make against your position. 
  
  socmedia:
    facebook:
      include_follow: false
      facebook_page: 
    twitter:
      include_follow: false
      twitter_page: 
  
  decisions:
    name: 
      short: levy component
      full: levy component
  
  footer:
    has_custom_resources: true
    resources:

      - title: Balance of opinions
        items:
          - anchor: Crosscut editorial
            link: http://crosscut.com/2011/06/23/seattle-schools/21042/Seattle-s-families-and-education-levy:-different-this-time/
            title: June 2011 editorial which covers both Pros and Cons of the levy
          - anchor: SLOG article
            link: http://slog.thestranger.com/slog/archives/2011/03/21/city-council-puts-families-and-education-levy-on-november-ballot
            title: includes info about tax increases
          - anchor: KUOW radio program
            link: http://www.kuow.org/program.php?id=22703
            title: 
            
      - title: Opposition
        items:
          - anchor: Policy Brief by Washington Policy Council
            link: http://www.washingtonpolicy.org/publications/brief/accountability-and-learning-assessing-seattle-families-and-education-levy
            title: Policy Brief by Washington Policy Council
          - anchor: Sound Politics
            link: http://www.soundpolitics.com/archives/cat_families_and_education_levy.html
            title: Has both pro and con responses from Seattle citizens, but at the moment more opposition
          - anchor: Seattle Times editorial
            link: http://seattletimes.nwsource.com/html/editorials/2014538312_edit20levy.html
            title: Written in advance
          - anchor: Seattle PI article
            link: http://www.seattlepi.com/default/article/Levy-doubling-taxes-for-Seattle-education-advances-1306382.php
            title: About Levy doubling taxes

      - title: Support
        items:
          - anchor: Editorial from Real Change
            link: http://www.realchangenews.org/index.php/site/archives/5694/
            title: Organization helping homeless and low-income
          - anchor: Yes! Families and Education Levy campaign
            link: http://www.familiesandeducationlevy.org/
            title: 
          - anchor: Office of Education
            link: http://www.cityofseattle.net/neighborhoods/education/
            title: Levy Info page
         
  
test: 
  default_to: development
  perform_authentication: true
  send_email: true


production:
  default_to: development
  perform_authentication: true
  send_email: true

