- name: Make .ssh directory
  file: path=~/.ssh owner=$user state=directory
  sudo: False

- name: Copy over private rsa deploy key
  copy: src=files/${deploy_key}_rsa dest=~/.ssh/${deploy_key}_rsa mode=700
  sudo: False

- name: Add ssh key to config file
  template: src=templates/ssh_config.j2 dest=~/.ssh/config
  sudo: False

# - name: Add Github to known hosts
#   copy: src=templates/ssh_known_hosts dest=~/.ssh/known_hosts
#   sudo: False

# - name: Installs ConsiderIt
#   git: repo=${code.repo} dest=$app_home version=${code.branch}
#   sudo: False

- name: Create database.yml
  template: src=templates/project/database.yml.j2 dest=$app_home/config/database.yml mode=400
  sudo: False

- name: Create local_environment.yml
  template: src=templates/project/local_environment.yml.j2 dest=$app_home/config/local_environment.yml mode=400
  sudo: False